### ISSUE TITLE
Can anyone help me with this data pull error?

### ISSUE THREAD

**Issue by rwitinokhuber** [erhs-r/group_6#6]
Trying to pull datasets into R Studio through our Data branch. Getting the error message bellow. Can someone help me identify what I'm doing wrong? 

>>> /usr/bin/git checkout -b Data origin/Data
error: The following untracked working tree files would be overwritten by checkout:
	.gitignore
Please move or remove them before you switch branches.
Aborting

I tried to switch from the main to data branch and got this error message:

>>> /usr/bin/git checkout -b Data origin/Data
error: The following untracked working tree files would be overwritten by checkout:
	.gitignore
Please move or remove them before you switch branches.
Aborting

@kaileejreed @bwenck @nickgood

**Comment by nickgood** [comment]
@rwitinokhuber it looks like its being grumpy because of the gitignore file. You have two options: remove the gitignore file from your computer and sync to the one on GitHub or remove the one on GitHub and make sure you all stop tracking that file. I'd start with the first option and see if that works for your group (we can walk through the steps if needed in class).
